# Generated by Django 3.0.5 on 2020-04-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('books', '0002_auto_20200414_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('maxread', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-c_time'],
            },
        ),
    ]
