# Generated by Django 3.0.5 on 2020-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='author',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='maxread',
        ),
        migrations.AlterField(
            model_name='collect',
            name='c_time',
            field=models.DateTimeField(),
        ),
    ]
