# Generated by Django 3.0.5 on 2020-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_img',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
